# Generated by Django 5.0.1 on 2024-02-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_persondesc_color_skin_persondesc_ethnicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondesc',
            name='color_skin',
            field=models.CharField(choices=[('blanca', 'Blanca'), ('mulata', 'Mulata'), ('rubia', 'Rubia'), ('negra', 'Morena oscura')], default='Blanca', max_length=20),
        ),
        migrations.AlterField(
            model_name='persondesc',
            name='eyes_color',
            field=models.CharField(choices=[('azul', 'Azules'), ('verde', 'Verdes'), ('cafe', 'Café'), ('ambar', 'Ámbar'), ('gris', 'grises'), ('avellana', 'Avellana'), ('otro', 'Otros')], default='Azules', max_length=20),
        ),
    ]
